#!/bin/bash
action=$1
target=$2
args=$@

BASE_DIR=/opt
ORIGINAL_PORT=9999
ORIGINAL_VERSION=v1.0.0
ORIGINAL_ENTRANCE=entrance
ORIGINAL_USERNAME=username
ORIGINAL_PASSWORD=password

function usage() {
    echo "1Panel Control Script"
    echo
    echo "Usage: "
    echo "  ./1pctl [COMMAND] [ARGS...]"
    echo "  ./1pctl --help"
    echo
    echo "Commands: "
    echo "  status              Check 1Panel service status"
    echo "  start               Start 1Panel service"
    echo "  stop                Stop 1Panel service"
    echo "  restart             Restart 1Panel service"
    echo "  uninstall           Remove 1Panel service"
    echo "  user-info           Get 1Panel user information"
    echo "  listen-ip           switch 1Panel IP"
    echo "  version             View 1Panel version info"
    echo "  update              Update 1Panel data"
    echo "  reset               Rest 1Panel date"
    echo "  restore             Restore 1Panel services and data"
}
function status() {
    systemctl status 1panel.service
}
function start() {
    systemctl start 1panel.service
    status
}
function stop() {
    systemctl stop 1panel.service
    status
}
function restart() {
    systemctl restart 1panel.service
    status
}
function uninstall() {
    read -p "This option will completely remove 1Panel service and related files, are you sure you want to continue? [y/n] : " yn
    if [ "$yn" == "Y" ] || [ "$yn" == "y" ]; then
        echo -e "================== Removing 1Panel Linux server management panel =================="
        echo -e ""
        echo -e "1) Stopping 1Panel service..."
        systemctl stop 1panel.service
        systemctl disable 1panel.service >/dev/null 2>&1
    else
        exit 0
    fi

    echo -e "2) Removing 1Panel service and related files..."
    rm -rf $BASE_DIR/1panel /usr/local/bin/{1pctl,1panel} /etc/systemd/system/1panel.service

    echo -e "3) Reloading the service manager..."
    systemctl daemon-reload
    systemctl reset-failed

    echo -e ""
    echo -e "================================== 1Panel Removed =================================="
}
function user-info() {
    1panel user-info
}
function listen-ip() {
    1panel listen-ip
}
function listen_ipv4() {
    1panel listen-ip ipv4
    restart
}
function listen_ipv6() {
    1panel listen-ip ipv6
    restart
}
function restore() {
    read -p "1Panel will be restored to last version, are you sure you want to continue? [y/n] : " yn
    if [ "$yn" == "Y" ] || [ "$yn" == "y" ]; then
        echo -e ""
        1panel restore
        systemctl daemon-reload
        restart
        echo -e ""
        1panel version
    else
        exit 0
    fi
}
function version() {
    1panel version
}
function reset() {
    1panel reset
}
function reset_domain() {
    1panel reset domain
}
function reset_entrance() {
    1panel reset entrance
}
function reset_https() {
    1panel reset https
    restart
}
function reset_ips() {
    1panel reset ips
}
function reset_mfa() {
    1panel reset mfa
}
function update() {
    1panel update
}
function update_username() {
    1panel update username
}
function update_password() {
    1panel update password
}
function update_port() {
    1panel update port
}

function main() {
    case "${action}" in
        status)
            status
            ;;
        start)
            start
            ;;
        stop)
            stop
            ;;
        restart)
            restart
            ;;
        restore)
            restore
            ;;
        uninstall)
            uninstall
            ;;
        user-info)
            user-info
            ;;
        listen-ip)
            case "${target}" in
                ipv4)
                    listen_ipv4
                    ;;
                ipv6)
                    listen_ipv6
                    ;;
                *)
                    listen-ip
                    ;;
            esac
            ;;
        version)
            version
            ;;
        reset)
            case "${target}" in
                domain)
                    reset_domain
                    ;;
                entrance)
                    reset_entrance
                    ;;
                https)
                    reset_https
                    ;;
                ips)
                    reset_ips
                    ;;
                mfa)
                    reset_mfa
                    ;;
                *)
                    reset
                    ;;
            esac
            ;;
        update)
            case "${target}" in
                username)
                    update_username
                    ;;
                password)
                    update_password
                    ;;
                port)
                    update_port
                    ;;
                *)
                    update
                    ;;
            esac
            ;;
        help)
            usage
            ;;
        --help)
            usage
            ;;
        "")
            usage
            ;;
        *)
        echo "Invalid argument, please use help or --help to print the help menu"
    esac
}
main
