#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=15

start_service() {
    procd_open_instance
    procd_set_param command 1panel
    procd_set_param stdout 0 # 默认设置不输出系统日志，如为1，在系统日志可看到1panel前端响应信息
    procd_set_param stderr 1
    procd_close_instance
